version: 0.2
phases:
  pre_build:
    commands:
      - echo Downloading PaperMod theme on $(date)
      - rm -rf themes/PaperMod
      - git clone --depth 1 --branch v8.0 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
  build:
    commands:
      - echo Build started on $(date)
      - hugo --minify
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  type: zip
  files:
    - '**/*'
  name: sebinthecloud-$(date +%Y%m%d%H%M%S).zip
  base-directory: 'public'
cache:
  paths:
    - 'resources/**/*'
