version: 0.2
phases:
  pre_build:
    commands:
      - echo Initializing git submodules on $(date)
      - git submodule update --init --recursive --depth 1
  build:
    commands:
      - echo Build started on $(date)
      - hugo --minify
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  type: zip
  files:
    - '**/*'
  name: sebinthecloud-$(date +%Y%m%d%H%M%S).zip
  base-directory: 'public'
cache:
  paths:
    - 'resources/**/*'
