version: 0.2
phases:
  install:
    commands:
      - wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.147.6/hugo_extended_0.147.6_linux-amd64.tar.gz | tar xz -C /usr/local/bin
      - hugo version
  build:
    commands:
      - echo Build started on $(date)
      - hugo --minify
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  type: zip
  files:
    - '**/*'
  name: sebinthecloud-$(date +%Y%m%d%H%M%S).zip
  base-directory: 'public'
cache:
  paths:
    - 'resources/**/*'
